### ISSUE TITLE
Elastic search error on PUT /datasets/corrections/pits

### ISSUE THREAD

**Issue by por** [transparantnederland/api#19]
Adding a PIT correction results in an Elasticsearch error, which causes subsequent searches for the same PIT to crash. Meanwhile, Neo4j does add a new corrections PIT and relation correctly. Any ideas @tomdemeyer?

``` sh
curl -i -u admin -X PUT -H "Content-Type: application/json" -d '{"id": "urn:hgid:nevenfuncties/Nyux-yFWShfx", "type": "tnl:Public", "_correction_id": "shabasedontimestamp"}' http://localhost:3001/datasets/corrections/pits
```

```
{ [Error: [index_already_exists_exception] already exists, with: {"index":"z_corrections_"}]
  status: '400',
  message: '[index_already_exists_exception] already exists, with: {"index":"z_corrections_"}',
  path: '/z_corrections_',
  query: {},
  body: '{"settings":{"number_of_shards":5,"number_of_replicas":0,"analysis":{"analyzer":{"lowercase":{"type":"custom","filter":" lowercase","tokenizer":"keyword"}}}},"mappings":{"_default_":{"properties":{"geometry":{"precision":"1m","tree":"quadtree","type":"geo_shape"},"uri":{"index":"not_analyzed","type":"string"},"id":{"index":"not_analyzed","store":true,"type":"string"},"type":{"index":"not_analyzed","type":"string"},"name":{"fields":{"analyzed":{"index":"analyzed","store":true,"type":"string"},"exact":{"analyzer":"lowercase","store":true,"type":"string"}},"type":"string"},"dataset":{"index":"not_analyzed","type":"string"},"validSince":{"format":"date_optional_time","type":"date"},"validUntil":{"format":"date_optional_time","type":"date"}}}}}',
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"already exists","index":"z_corrections_"}],"type":"index_already_exists_exception","reason":"already exists","index":"z_corrections_"},"status":400}',
  toString: [Function],
  toJSON: [Function] } '[index_already_exists_exception] already exists, with: {"index":"z_corrections_"}'
```

**Comment by por** [comment]
We’re probably only seeing this error on PITs because relations are not stored in Elasticsearch. I haven’t worked with Elasticsearch before, so I don’t know any of the concepts. I can investigate further to understand the problem fully. Would still be good to have some @tomdemeyer eyes on this. :eyeglasses:

**Comment by wires** [comment]
ES most of the time is set to automatically create an index (optionally using a template), strangely enough it also does this when you delete a document. On AWS we cannot use this template functionality, so we have to create the indices "manually". That is, the IO project does this when a new dataset is created. Due to some race condition the dataset creation part (in IO) and object insertion (in core/graphmalizer) can get out of order and this can cause troubles. Furthermore, one can check before if the index already exists and if now, create it. Alternatively, we can just create it and ignore the error if it already exists. This turns out to be faster... All in all, it shouldn't interfere with indexing and I think this can be fixed when core+io is rewritten...

**Comment by por** [comment]
@wires so what would be the quick fix for this? This happens when we try to import a PIT on a ‘corrections’ dataset.

**Comment by por** [comment]
Stefano is working on this in Histograph Core.
